app: mc-xp-bank
org: ryanallen

service: mc-xp-bank

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  role: arn:aws:iam::425071954352:role/service-role/mc-microservice-role
  environment:
    LOGGER_ENABLED: true
    TABLE_XP:
      Ref:
        - XpDatabase

functions:
  teller:
    handler: src/index.handler
    events:
      - httpApi:
          path: /xp/query
          method: get
      - httpApi:
          path: /xp/balance
          method: get
      - httpApi:
          path: /xp/deposit
          method: post
      - httpApi:
          path: /xp/withdraw
          method: post
      - httpApi:
          path: /xp/transfer
          method: post
resources:
  Resources:
    XpDatabase:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: "userId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "userId"
            KeyType: "HASH"
        BillingMode: "PAY_PER_REQUEST"