app: mc-xp-bank
org: ryanallen

service: mc-xp-bank

frameworkVersion: '2'

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  iam:
    role: arn:aws:iam::425071954352:role/service-role/mc-microservice-role
  environment:
    LOGGER_ENABLED: ${env:LOGGER_ENABLED}
    SERVER_HOST: ${env:SERVER_HOST}
    SERVER_RCON_PORT: ${env:SERVER_RCON_PORT}
    SERVER_RCON_PASS: ${env:SERVER_RCON_PASS}
    SERVER_RCON_TIMEOUT_MS: ${env:SERVER_RCON_TIMEOUT_MS}
    TABLE_XP: #${env:TABLE_XP}
      Ref:
        - XpDatabase
    FEATURE_ENABLED_ESSENTIALS_X_PLUGIN: ${env:FEATURE_ENABLED_ESSENTIALS_X_PLUGIN}

functions:
  teller:
    handler: src/index.handler
    events:
      - httpApi:
          path: /xp/query
          method: get
      - httpApi:
          path: /xp/balance
          method: get
      - httpApi:
          path: /xp/deposit
          method: post
      - httpApi:
          path: /xp/withdraw
          method: post
      - httpApi:
          path: /xp/transfer
          method: post
resources:
  Resources:
    XpDatabase:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: "userId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "userId"
            KeyType: "HASH"
        BillingMode: "PAY_PER_REQUEST"