
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.2
  serverless: circleci/serverless-framework@1.0.1
  discord: antonioned/discord@0.1.0

jobs:
  build-and-test:
    docker:
      - image: 'circleci/node:12.19.0'
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Codecov
          command: sudo npm install -g codecov
      - run: 
          name: Test
          command: npm run test
      - run:
          name: Report Coverage
          command: npm run report-coverage
      - discord/status:
          webhook: ${CICD_WEBHOOK_URL}
          fail_only: true
  deploy-dev:
    executor: serverless/default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - aws-cli/setup
      - serverless/setup:
          app-name: mc-xp-bank
          org-name: ryanallen
      - run:
          command: serverless deploy --stage dev
          name: deploy
      - discord/status:
          webhook: ${CICD_WEBHOOK_URL}
  deploy-prod:
    executor: serverless/default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - aws-cli/setup
      - serverless/setup:
          app-name: mc-xp-bank
          org-name: ryanallen
      - run:
          command: serverless deploy --stage prod
          name: deploy
      - discord/status:
          webhook: ${CICD_WEBHOOK_URL}

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-test
      - deploy-dev:
          context: 
            - craftonomy-dev
            - mc-xp-bank-dev
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - develop
      - deploy-prod:
          context: 
            - craftonomy-prod
            - mc-xp-bank-prod
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
