@startuml sequence_deposit_direct

title Sequence: Deposit XP

collections McSteve
collections McXpBankTeller
database XpAccounts
collections GameServer

McSteve -> McXpBankTeller: POST /xp/deposit (userId, amount)
alt non-positive amount
    McSteve <-- McXpBankTeller: HTTP 400
end

McXpBankTeller -> GameServer: rcon(queryXpInLevels(userId))
McXpBankTeller -> GameServer: rcon(queryXpInPoints(userId))
alt commands success
    McXpBankTeller <-- GameServer: Success Responses
    McXpBankTeller -> McXpBankTeller: calculateXpInPoints(levels, points)
    alt player has enough XP
        McXpBankTeller -> GameServer: rcon(xpRemoveInPoints(userId, amount))
        alt command success
            McXpBankTeller <-- GameServer: Success Response
            McXpBankTeller -> XpAccounts: update(userId, increment(amount))
            McSteve <-- McXpBankTeller: HTTP 200
        else command failure
            McSteve <-- McXpBankTeller: HTTP 500
        end
    else player has insufficient XP
        McSteve <-- McXpBankTeller: HTTP 403
    end
else commands failure
    McXpBankTeller -> McSteve: HTTP 500
end

@enduml
